In [1]:
!pip install --upgrade --force-reinstall git+https://github.com/FelipeSchreiber/BregmanClustering.git

  Cloning https://github.com/FelipeSchreiber/BregmanClustering.git to /tmp/pip-req-build-ubp7_wja
  Running command git clone --filter=blob:none --quiet https://github.com/FelipeSchreiber/BregmanClustering.git /tmp/pip-req-build-ubp7_wja
  Resolved https://github.com/FelipeSchreiber/BregmanClustering.git to commit 06ce93faf89c6113e802bda343c39d8e165de782
  Preparing metadata (setup.py) ... done
  Created wheel for bregClust: filename=bregClust-0.1-py3-none-any.whl size=10462 sha256=c266c0777a9add0a8be918a7ef0cce87e65e888d0b0806d4fcf5ebfc6953d334
  Stored in directory: /tmp/pip-ephem-wheel-cache-es0qzl_9/wheels/6f/8f/ab/2faa84d8b9fad58989d72cda12225f6191888313b2d42f6ad5
Successfully built bregClust
  Attempting uninstall: bregClust
    Found existing installation: bregClust 0.1
    Uninstalling bregClust-0.1:
      Successfully uninstalled bregClust-0.1


In [2]:
from sklearn.manifold import spectral_embedding,SpectralEmbedding
from sklearn.mixture import GaussianMixture
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score, accuracy_score
from BregmanClustering.models import SoftBregmanNodeAttributeGraphClustering as VEMbreg
from sklearn.metrics import adjusted_rand_score, calinski_harabasz_score, normalized_mutual_info_score, accuracy_score
from BregmanClustering.WSBM import *

In [3]:
c = 3
n = 100
N = c*n
delta = 10
d = 2
dim = c*d
P = np.array([[0.8, 0.2, 0.3],[0.2, 0.7, 0.4],[0.3, 0.4, 0.6]])
true_labels = [0]*n + [1]*n + [2]*n
X,Y= BregmanBenchmark(P,[n]*c,-10,10,dims=2,weight_variance=0.01,att_variance=0.1,\
                       weight_distribution="logistic",attributes_distribution="logistic").generate_benchmark_WSBM()
A = (X != 0).astype(int)

In [4]:
model = VEMbreg(n_clusters=c,thresholding=False,normalize_=False)
model.fit(A,Y)
z_pred_both = model.predict(A,Y)
print(adjusted_rand_score(true_labels, z_pred_both),normalized_mutual_info_score(true_labels, z_pred_both))

[[0.6002 0.4037 0.2988]
 [0.4037 0.69   0.2024]
 [0.2988 0.2024 0.7956]]
Initialisation chosen from the graph
0
[[1.94077184e+00 2.17885389e+00 3.91138026e-01]
 [1.62271868e+00 1.59853904e+00 1.90537555e-01]
 [1.68909307e+00 1.28666658e+00 5.29256415e-01]
 [1.95645229e+00 2.12282716e+00 3.39919419e-01]
 [2.20109684e+00 1.90657010e+00 5.07416949e-01]
 [1.35042493e+00 1.71836567e+00 3.84799576e-01]
 [1.73049526e+00 1.68177659e+00 1.22718783e-01]
 [2.30439092e+00 1.75835632e+00 7.16544470e-01]
 [1.44672911e+00 2.31886117e+00 8.54569212e-01]
 [2.02774647e+00 2.03432502e+00 3.18233956e-01]
 [1.83614692e+00 1.74726964e+00 1.55828390e-01]
 [2.80706473e+00 2.64923529e+00 1.10013839e+00]
 [1.41348734e+00 1.42602503e+00 4.11826315e-01]
 [1.67476173e+00 1.75210301e+00 5.16657858e-02]
 [1.52725873e+00 2.15594995e+00 5.82753221e-01]
 [1.75129097e+00 1.95984805e+00 1.85859471e-01]
 [2.33312170e+00 2.31855854e+00 6.42344553e-01]
 [1.58189892e+00 1.60806334e+00 1.94041116e-01]
 [1.78565921e+00 1.59274

[[1.3369802  1.3369802  1.3369802 ]
 [0.81268943 0.81268943 0.81268943]
 [0.72176512 0.72176512 0.72176512]
 [1.30961583 1.30961583 1.30961583]
 [1.34435389 1.34435389 1.34435389]
 [0.75371585 0.75371585 0.75371585]
 [0.92715327 0.92715327 0.92715327]
 [1.36694386 1.36694386 1.36694386]
 [1.28611364 1.28611364 1.28611364]
 [1.29659637 1.29659637 1.29659637]
 [1.02880623 1.02880623 1.02880623]
 [2.05709714 2.05709714 2.05709714]
 [0.57452122 0.57452122 0.57452122]
 [0.93446658 0.93446658 0.93446658]
 [1.16451808 1.16451808 1.16451808]
 [1.10560605 1.10560605 1.10560605]
 [1.62066504 1.62066504 1.62066504]
 [0.79287949 0.79287949 0.79287949]
 [0.91897987 0.91897987 0.91897987]
 [0.7579894  0.7579894  0.7579894 ]
 [0.7577438  0.7577438  0.7577438 ]
 [1.11407285 1.11407285 1.11407285]
 [1.1704409  1.1704409  1.1704409 ]
 [1.3120036  1.3120036  1.3120036 ]
 [0.68877242 0.68877242 0.68877242]
 [1.18330711 1.18330711 1.18330711]
 [0.71756223 0.71756223 0.71756223]
 [1.39402647 1.39402647 1.39