In [1]:
# !pip3 install cupy

In [2]:
from sklearn.manifold import spectral_embedding,SpectralEmbedding
from sklearn.mixture import GaussianMixture
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score, accuracy_score
from BregmanClustering.models import SoftBregmanNodeAttributeGraphClustering as VEMbreg
from sklearn.metrics import adjusted_rand_score, calinski_harabasz_score, normalized_mutual_info_score, accuracy_score
from BregmanClustering.WSBM import *

In [3]:
c = 3
n = 100
N = c*n
delta = 10
d = 2
dim = c*d
P = np.array([[0.8, 0.2, 0.3],[0.2, 0.7, 0.4],[0.3, 0.4, 0.6]])
true_labels = [0]*n + [1]*n + [2]*n
X,Y= BregmanBenchmark(P,[n]*c,-10,10,dims=2,weight_variance=0.01,att_variance=0.1,\
                       weight_distribution="logistic",attributes_distribution="logistic").generate_benchmark_WSBM()
A = (X != 0).astype(int)

In [4]:
model = VEMbreg(n_clusters=c,thresholding=True,normalize_=False)
model.fit(A,Y)
z_pred_both = model.predict(A,Y)
print(adjusted_rand_score(true_labels, z_pred_both),normalized_mutual_info_score(true_labels, z_pred_both))

[[0.69   0.4037 0.2024]
 [0.4037 0.6002 0.2988]
 [0.2024 0.2988 0.7956]]
Initialisation chosen from the graph
0
1.0 1.0
