In [1]:
!pip install torch_geometric
!pip install --upgrade --force-reinstall git+https://github.com/FelipeSchreiber/BregmanClustering.git --no-deps

  Cloning https://github.com/FelipeSchreiber/BregmanClustering.git to /tmp/pip-req-build-eloychoy
  Running command git clone --filter=blob:none --quiet https://github.com/FelipeSchreiber/BregmanClustering.git /tmp/pip-req-build-eloychoy
  Resolved https://github.com/FelipeSchreiber/BregmanClustering.git to commit 40cd47d5524a6c6ba65bb53cf8ee1a5d1f3e1a6d
  Preparing metadata (setup.py) ... done
  Created wheel for bregClust: filename=bregClust-0.1-py3-none-any.whl size=10597 sha256=2648b28dd0a32ffd60d1f2a8414ee46c730aeda1f462196e98a5e324e8e79d52
  Stored in directory: /tmp/pip-ephem-wheel-cache-nktd591r/wheels/6f/8f/ab/2faa84d8b9fad58989d72cda12225f6191888313b2d42f6ad5
Successfully built bregClust
  Attempting uninstall: bregClust
    Found existing installation: bregClust 0.1
    Uninstalling bregClust-0.1:
      Successfully uninstalled bregClust-0.1


In [2]:
from BregmanClustering.models import SoftBregmanNodeAttributeGraphClustering as VEMbreg
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score
from BregmanTests.WSBM import *
from BregmanClusteringTorch.torch_models import SoftBregmanClusteringTorch as torchBreg

In [3]:
c = 3
n = 100
N = c*n
r = 10
d = 2
P = np.array([[0.8, 0.2, 0.3],[0.2, 0.7, 0.4],[0.3, 0.4, 0.6]])
X,Y,true_labels = BregmanBenchmark(P,[n]*c,-10,10,dims=d,weight_variance=0.01,att_variance=0.1,\
                       weight_distribution="logistic",attributes_distribution="logistic",radius=r).generate_benchmark_WSBM()
A = (X != 0).astype(int)

In [8]:
model = torchBreg(n_clusters=c,thresholding=True,normalize_=True)
model.fit(A,Y)
z_pred_both = model.predict(A,Y)
print(adjusted_rand_score(true_labels, z_pred_both),normalized_mutual_info_score(true_labels, z_pred_both))

Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7f554850b940>
Traceback (most recent call last):
  File "/home/felipe/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/home/felipe/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/home/felipe/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/home/felipe/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.mat

[[0.69   0.2024 0.4037]
 [0.2024 0.7956 0.2988]
 [0.4037 0.2988 0.6002]]
Initialisation chosen from the graph
0
1.0 1.0
